### ISSUE TITLE
Bug in generating analytics

### ISSUE THREAD

**Issue by abhishek-v-gopal** [decoded-cipher/mgu-result-scraper#15]
![image](https://github.com/decoded-cipher/mgu-result-scraper/assets/115163920/531420ea-6ea4-43d1-a3a8-39ab8ed7363d)
When I try to run the program the analytics is not working properly all other function is done correctly and all the data is inserted into DB

**Comment by abhishek-v-gopal** [comment]
BUG

**Comment by decoded-cipher** [comment]
Issue resolved...
